//
//  Language.swift
//  Baluchon
//
//  Created by François-Xavier on 14/11/2023.
//

import Foundation

enum Language: String {
    case afrikaans = "af"
    case albanian = "sq"
    case amharic = "am"
    case arabic = "ar"
    case armenian = "hy"
    case assamese = "as"
    case aymara = "ay"
    case azerbaijani = "az"
    case bambara = "bm"
    case basque = "eu"
    case belarusian = "be"
    case bengali = "bn"
    case bhojpuri = "bho"
    case bosnian = "bs"
    case bulgarian = "bg"
    case catalan = "ca"
    case cebuano = "ceb"
    case simplifiedChinese = "zh-CN"
    case traditionalChinese = "zh-TW"
    case corsican = "co"
    case croatian = "hr"
    case czech = "cs"
    case danish = "da"
    case dhivehi = "dv"
    case dogri = "doi"
    case dutch = "nl"
    case english = "en"
    case esperanto = "eo"
    case estonian = "et"
    case ewe = "ee"
    case filipino = "fil"
    case finnish = "fi"
    case french = "fr"
    case frisian = "fy"
    case galician = "gl"
    case georgian = "ka"
    case german = "de"
    case greek = "el"
    case guarani = "gn"
    case gujarati = "gu"
    case haitianCreole = "ht"
    case hausa = "ha"
    case hawaiian = "haw"
    case hebrew = "he"
    case hindi = "hi"
    case hmong = "hmn"
    case hungarian = "hu"
    case icelandic = "is"
    case igbo = "ig"
    case ilocano = "ilo"
    case indonesian = "id"
    case irish = "ga"
    case italian = "it"
    case japanese = "ja"
    case javanese = "jv"
    case kannada = "kn"
    case kazakh = "kk"
    case khmer = "km"
    case kinyarwanda = "rw"
    case konkani = "gom"
    case korean = "ko"
    case krio = "kri"
    case kurdish = "ku"
    case kurdishSorani = "ckb"
    case kyrgyz = "ky"
    case lao = "lo"
    case latin = "la"
    case latvian = "lv"
    case lingala = "ln"
    case lithuanian = "lt"
    case luganda = "lg"
    case luxembourgish = "lb"
    case macedonian = "mk"
    case maithili = "mai"
    case malagasy = "mg"
    case malay = "ms"
    case malayalam = "ml"
    case maltese = "mt"
    case maori = "mi"
    case marathi = "mr"
    case meitei = "mni-Mtei"
    case mizo = "lus"
    case mongolian = "mn"
    case burmese = "my"
    case nepali = "ne"
    case norwegian = "no"
    case nyanja = "ny"
    case odia = "or"
    case oromo = "om"
    case pashto = "ps"
    case persian = "fa"
    case polish = "pl"
    case portuguese = "pt"
    case punjabi = "pa"
    case quechua = "qu"
    case romanian = "ro"
    case russian = "ru"
    case samoan = "sm"
    case sanskrit = "sa"
    case scotsGaelic = "gd"
    case sepedi = "nso"
    case serbian = "sr"
    case sesotho = "st"
    case shona = "sn"
    case sindhi = "sd"
    case sinhala = "si"
    case slovak = "sk"
    case slovenian = "sl"
    case somali = "so"
    case spanish = "es"
    case sundanese = "su"
    case swahili = "sw"
    case swedish = "sv"
    case tagalogPhilippine = "tl"
    case tajik = "tg"
    case tamil = "ta"
    case tatar = "tt"
    case telugu = "te"
    case thai = "th"
    case tigrinya = "ti"
    case tsonga = "ts"
    case turkish = "tr"
    case turkmen = "tk"
    case twi = "ak"
    case ukrainian = "uk"
    case urdu = "ur"
    case uighur = "ug"
    case uzbek = "uz"
    case vietnamese = "vi"
    case welsh = "cy"
    case xhosa = "xh"
    case yiddish = "yi"
    case yoruba = "yo"
    case zulu = "zu"
    
    static let allCases: [Language] = [
        .afrikaans, .albanian, .amharic, .arabic, .armenian, .assamese, .aymara, .azerbaijani, .bambara, .basque,
        .belarusian, .bengali, .bhojpuri, .bosnian, .bulgarian, .catalan, .cebuano, .simplifiedChinese, .traditionalChinese,
        .corsican, .croatian, .czech, .danish, .dhivehi, .dogri, .dutch, .english, .esperanto, .estonian, .ewe, .filipino,
        .finnish, .french, .frisian, .galician, .georgian, .german, .greek, .guarani, .gujarati, .haitianCreole, .hausa,
        .hawaiian, .hebrew, .hindi, .hmong, .hungarian, .icelandic, .igbo, .ilocano, .indonesian, .irish, .italian, .japanese,
        .javanese, .kannada, .kazakh, .khmer, .kinyarwanda, .konkani, .korean, .krio, .kurdish, .kurdishSorani, .kyrgyz, .lao,
        .latin, .latvian, .lingala, .lithuanian, .luganda, .luxembourgish, .macedonian, .maithili, .malagasy, .malay, .malayalam,
        .maltese, .maori, .marathi, .meitei, .mizo, .mongolian, .burmese, .nepali, .norwegian, .nyanja, .odia, .oromo, .pashto, .persian,
        .polish, .portuguese, .punjabi, .quechua, .romanian, .russian, .samoan, .sanskrit, .scotsGaelic, .sepedi, .serbian, .sesotho,
        .shona, .sindhi, .sinhala, .slovak, .slovenian, .somali, .spanish, .sundanese, .swahili, .swedish, .tagalogPhilippine, .tajik,
        .tamil, .tatar, .telugu, .thai, .tigrinya, .tsonga, .turkish, .turkmen, .twi, .ukrainian, .urdu, .uighur, .uzbek, .vietnamese,
        .welsh, .xhosa, .yiddish, .yoruba, .zulu
    ]
}
